language: python
python:
  - "3.3"

# command to install dependencies
install:
  - pip3.3 install tweepy
  - pip3.3 install coverage
  - pip3.3 install python-coveralls

# command to run tests
script: coverage run run_tests.py
after_success: coveralls